### ISSUE TITLE
Defaults in \Mailchimp\MailchimpApiUser::request

### ISSUE THREAD

**Issue by primsi** [thinkshout/mailchimp-api-php#114]
https://github.com/thinkshout/mailchimp-api-php/blob/main/src/MailchimpApiUser.php#L156 has probably some leftover defaults from copy/paste. when calling api_class->request().

**Comment by yanniboi** [comment]
Any chance we could have a new release candidate asap? Currently we would need to target head of the module to get this bug fixed and some module maintainers might like to be able to target a release instead:

https://www.drupal.org/project/mailchimp/issues/3353670

Thanks a lot :smile:

**Comment by aprice42** [comment]
Thanks for the reminder @yanniboi! I just rolled a new release https://github.com/thinkshout/mailchimp-api-php/releases/tag/v3.0.0-rc5

**Comment by szeidler** [comment]
@aprice42 Thanks for fixing it. There hasn't been any release pushed to packagist.org, therefore Composer will not update the package https://packagist.org/packages/thinkshout/mailchimp-api-php

**Comment by aprice42** [comment]
We added the version number to the composer.json file in a recent update to help with that, and I forgot to change that for the last release. Just did and rolled another release and updated that and packagist can see it now. Sorry about that!

https://github.com/thinkshout/mailchimp-api-php/releases/tag/v3.0.0-rc6

**Comment by szeidler** [comment]
Thanks for that. I would recommend to not use the `version` tag in the composer.json specification. It's prone for human errors, because you always would need to align the version with the git tag at the right time. Packagist.org by default is able to use the git tags for making them available to the composer world. It can be either done manually for the project owners or automatically with a webhook, so that new git tags always get available in packagist.org shortly after they have been pushed: https://packagist.org/about
