### ISSUE TITLE
Issue with MailchimpLists->updateSegment

### ISSUE THREAD

**Issue by a-fro** [thinkshout/mailchimp-api-php#22]
While reviewing how the Drupal mailchimp module adds subscribers to lists, I see that `mailchimp_segment_batch_add_subscribers` calls `$mc_lists->updateSegment($list_id, $segment_id, $matched_segment->name, $parameters);`. I'm trying to call the API's `updateSegment` independently from the Drupal module to add a subscriber to a static segment, but it doesn't work. 

I'd prefer to use the [Segment Members REST service](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/members/#create-post_lists_list_id_segments_segment_id_members) instead. Is there a reason that you're using the Update Segment resource, rather than the [Segment Members](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/members/) sub-resource? If I create a PR to add that sub-resource to the PHP API, will you review and accept it?

**Comment by a-fro** [comment]
Pull request created. https://github.com/thinkshout/mailchimp-api-php/pull/23. As I mention there, I am unable to get either `updateSegment` or `mailchimp_segment_add_subscriber` to add a subscriber to a static segment. The functionality implemented in that pull request is working.

**Comment by ruscoe** [comment]
Thanks for the pull request. Looks good and has been merged in.

I don't think there's any reason we couldn't use `MailchimpLists::addSegmentMember()` rather than `MailchimpLists::UpdateSegment()`, so if you've already made that change in the Drupal module definitely feel free to submit a patch and I'll get it added.

Sounds like there's still a separate issue with updating segments that I'll look into in the meantime.

**Comment by a-fro** [comment]
Thanks Dan! For the Drupal modules, should I use a github pr, or a D.O. patch?

**Comment by ruscoe** [comment]
D.O. would be perfect.
