### ISSUE TITLE
Do you use semvar?

### ISSUE THREAD

**Issue by darthsteven** [thinkshout/mailchimp-api-php#68]
Hi it looks like your version numbers are semvar style, but in your 1.0.10 release there's this:

https://github.com/thinkshout/mailchimp-api-php/releases/tag/v1.0.10

> *POTENTIALLY BREAKING CHANGE*
> 
> The addStore() signature parameter order has changed. This may affect you if you have custom code using this method.

If you're following semvar then this should have been a v2.0.0 release, no?

**Comment by ruscoe** [comment]
We haven't been following semver strictly, but we should have been. You're right that a breaking change should have warranted a major version release.

I'm going to leave this release as it is because I know several projects are already using it. We'll try to better follow the standards with future releases.

**Comment by darthsteven** [comment]
Thanks for the clarification.
