### ISSUE TITLE
Mailchimp no longer returns 'detail' attribute used in MailchimpAPIException

### ISSUE THREAD

**Issue by ArturPugacescu** [thinkshout/mailchimp-api-php#94]
According to this error it looks like Mailchimp message json no longer includes the 'detail' attribute.
![Screenshot from 2020-04-23 16-35-40](https://user-images.githubusercontent.com/6882815/80105365-308c5500-8581-11ea-83ad-3d5ad8d74620.png)

**Comment by SurfinSpirit** [comment]
PR https://github.com/thinkshout/mailchimp-api-php/pull/95

**Comment by renatonascalves** [comment]
Their documentation seems to indicate the detail will be returned.

**Comment by mariacha** [comment]
Agreed: https://mailchimp.com/developer/marketing/docs/errors/

In the screenshot there, though, the error is a 503 akamai error. That's outside of the list of responses provided by mailchimp, and is instead an error message provided by akamai directly. See the example json from https://community.akamai.com/customers/s/question/0D50f00005q0YwMCAU/akamai-firewall-problem-cant-access-my-mailchimp-list-via-my-website-error-message-in-the-details?language=en_US

`{"type":"akamai_error_message","title":"akamai_503","status":503,"ref_no":"Reference Number: 00.810a1602.1540926155.206a7946"}`

status and title are set, but there's no 'detail'.

So the better fix would be to not drop the detail property entirely, since it will exist sometimes, but instead to throw the detail message in an if statement, like we're doing for [errors below these lines](https://github.com/thinkshout/mailchimp-api-php/pull/95/files#diff-7d2b2c46eeeaa2fa5a5a3d9f296d03f1b6123b28a453437adf8e9ed317d897c5R22). Like this:

```
     if (!empty($message_obj->detail)) {
        $message .= ' - ' . $message_obj->detail;
      }
```

**Comment by mariacha** [comment]
Merged https://github.com/thinkshout/mailchimp-api-php/pull/101 which should close this issue. I'll cut a new release shortly.
